SQS Increment service. Дмитрий Абрамов и Юрий Парадовский.
karvozavr/docker-aws-sqs pull request #1
Opened 2019-06-05 19:46 UTC by karvozavr

2019-06-10 18:59 UTC, TanVD requested changes

2019-06-10 18:59 UTC, TanVD commented on app/build.gradle
> +    compile group: 'com.amazonaws', name: 'aws-java-sdk', version: '1.11.564'
Do not use whole AWS SDK - use only needed services

2019-06-10 18:59 UTC, TanVD commented on app/build.gradle
> +    id 'org.jetbrains.kotlin.jvm' version '1.3.30'
Why not 31?

2019-06-10 18:59 UTC, TanVD commented on app/src/main/kotlin/ru/spb/hse/karvozavr/increment/QueueManager.kt
> +    public fun checkQueueExists(queueName: String): Boolean {
Public is not needed in Kotlin

2019-06-10 18:59 UTC, TanVD commented on app/src/main/kotlin/ru/spb/hse/karvozavr/increment/IncrementService.kt
> +    private val sqsManager = QueueManager()
Use `object` for such purposes

2019-06-10 19:42 UTC, karvozavr commented on app/build.gradle
> +    id 'org.jetbrains.kotlin.jvm' version '1.3.30'
Я не обновился вовремя и так сгенерилось.

2019-06-10 20:00 UTC, karvozavr commented on app/src/main/kotlin/ru/spb/hse/karvozavr/increment/QueueManager.kt
> +    public fun checkQueueExists(queueName: String): Boolean {
Fixed.

2019-06-10 20:08 UTC, karvozavr commented on app/src/main/kotlin/ru/spb/hse/karvozavr/increment/IncrementService.kt
> +    private val sqsManager = QueueManager()
Please, could you be more clear about purposes and the use case of `object` you meant?

2019-06-10 20:08 UTC, karvozavr commented on app/build.gradle
> +    id 'org.jetbrains.kotlin.jvm' version '1.3.30'
Fixed

2019-06-10 20:08 UTC, karvozavr commented on app/build.gradle
> +    compile group: 'com.amazonaws', name: 'aws-java-sdk', version: '1.11.564'
Fixed.

2019-06-12 09:29 UTC, TanVD commented on app/src/main/kotlin/ru/spb/hse/karvozavr/increment/IncrementService.kt
> +    private val sqsManager = QueueManager()
You are using QueueManager as a singleton. Take a look at the `object` construct in Kotlin - it is `out of the box` singleton.

2019-06-13 16:51 UTC, subject-name-here commented on app/src/main/kotlin/ru/spb/hse/karvozavr/increment/IncrementService.kt
> +    private val sqsManager = QueueManager()
fixed

2019-06-13 16:59 UTC, subject-name-here commented
@TanVD !

2020-03-09 17:06 UTC, merged